swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Place Ranking Generator
  license:
    name: MIT
host: wsil.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rankPlacesToLive:
    post:
      summary: Get ordered list of places to lived based on proximity to important places
      operationId: rankPlacesToLive
      consumes:
        - application/json
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - placesToLive
              - importantPlaces
            properties:
              placesToLive:
                description: The Google maps place IDs for places to live that will be ranked based on their proximity to the important places
                type: array
                items:
                  type: string
              importantPlaces:
                description: The Google maps place IDs the potential places to live will be evaluated against
                type: array
                items:
                  $ref: '#/definitions/ImportantPlace'
              travelModes:
                description: The types of modes of transport that the user is willing to take
                type: array
                items:
                  $ref: '#/definitions/TravelModesEnum'
      responses:
        "200":
          description: List of potential places to live, ranked by suitability
          schema:
            $ref: '#/definitions/PlaceRankSummaries'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /rankPlacesToLiveStub:
    $ref: '#/paths/~1rankPlacesToLive'
definitions:
  ImportantPlace:
    type: "object"
    required:
      - id
      - visitsPerMonth
    properties:
      id:
        type: string
        description: Google Maps place id
      visitsPerMonth:
        type: number
        format: float
        description: Number of times this place is visited in one month
  TravelModesEnum:
    type: string
    enum: [driving, public_transport, cycling, walking]
  PlaceRankSummary:
    type: "object"
    required:
      - name
      - success
      - totalTravelTimePerMonth
      - journeySummaries
    properties:
      name:
        type: string
        description: Google Maps place name
      success:
        type: boolean
        description: Whether a sucessful distance matrix element was returned for this place
      totalTravelTimePerMonth:
        type: number
        format: float
        description: Total time over a month travelling if lived at the place with associated id
      fastestJourneys:
        description: Provides information about the shortest journey between the place to live and each important place
        type: array
        items:
          $ref: '#/definitions/JourneySummary'            
  PlaceRankSummaries:
    type: array
    items:
      $ref: '#/definitions/PlaceRankSummary'
  JourneySummary:
    type: object
    required:
      - name
      - success
      - travelMode
      - travelTime
    properties:
      name:
        type: string
        description: Google Maps place name
      success:
        type: boolean
        description: Whether a route was found between this important place and the corresponding place to live
      travelMode:
        description: Travel mode that resulted in the shortest travel time
        $ref: '#/definitions/TravelModesEnum'
      travelTime:
        description: Amount of time spent travelling
        type: number
        format: float
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string